# Generated by Django 2.1.5 on 2019-01-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecream',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
